name: Deploy to Production

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_and_deploy:
    name: Build package and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 2. Install NPM Dependencies & Build
      - name: Install NPM Dependencies & Build
        run: |
          npm ci
          npm run build

      # 3. Deploy to FTP hosting
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          timeout: 120000
          local-dir: ./dist/
          exclude: |
            **/.git*
            **/.git*/**
            README.md
